OBJS-${CONFIG_HEVC_DECODER} += riscv/hevcdsp_init_riscv.o
RVV-OBJS-${CONFIG_HEVC_DECODER} += riscv/hevcdsp_rvv.o

OBJS-${CONFIG_HEVC_DECODER} += riscv/hevcpred_init_riscv.o
RVV-OBJS-${CONFIG_HEVC_DECODER} += riscv/hevcpred_rvv.o